<?php
/**
 * BlockOutTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Patrick Leijser
 * @link     http://patrickleijser.nl
 */

/**
 * Kigo Core API
 *
 * https://www.kigoapis.com/core/v0.8/swagger/
 *
 * The version of the Kigo Core API: v0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\Kigo;

use PHPUnit\Framework\TestCase;

/**
 * BlockOutTest Class Doc Comment
 *
 * @category    Class
 * @description BlockOut
 * @package     Piksel\Kigo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BlockOutTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BlockOut"
     */
    public function testBlockOut()
    {
    }

    /**
     * Test attribute "property_id"
     */
    public function testPropertyPropertyId()
    {
    }

    /**
     * Test attribute "unit_id"
     */
    public function testPropertyUnitId()
    {
    }

    /**
     * Test attribute "check_in_date"
     */
    public function testPropertyCheckInDate()
    {
    }

    /**
     * Test attribute "check_in_time_minutes_from_midnight"
     */
    public function testPropertyCheckInTimeMinutesFromMidnight()
    {
    }

    /**
     * Test attribute "check_out_date"
     */
    public function testPropertyCheckOutDate()
    {
    }

    /**
     * Test attribute "check_out_time_minutes_from_midnight"
     */
    public function testPropertyCheckOutTimeMinutesFromMidnight()
    {
    }

    /**
     * Test attribute "private_notes"
     */
    public function testPropertyPrivateNotes()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }
}
