<?php
/**
 * PropertyAmenityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Patrick Leijser
 * @link     http://patrickleijser.nl
 */

/**
 * Kigo Core API
 *
 * https://www.kigoapis.com/core/v0.8/swagger/
 *
 * The version of the Kigo Core API: v0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\Kigo;

use PHPUnit\Framework\TestCase;

/**
 * PropertyAmenityTest Class Doc Comment
 *
 * @category    Class
 * @description PropertyAmenity
 * @package     Piksel\Kigo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PropertyAmenityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PropertyAmenity"
     */
    public function testPropertyAmenity()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "popularity_rank"
     */
    public function testPropertyPopularityRank()
    {
    }

    /**
     * Test attribute "is_baseline"
     */
    public function testPropertyIsBaseline()
    {
    }
}
