<?php
/**
 * PropertyReviewTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Patrick Leijser
 * @link     http://patrickleijser.nl
 */

/**
 * Kigo Core API
 *
 * https://www.kigoapis.com/core/v0.8/swagger/
 *
 * The version of the Kigo Core API: v0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\Kigo;

use PHPUnit\Framework\TestCase;

/**
 * PropertyReviewTest Class Doc Comment
 *
 * @category    Class
 * @description PropertyReview
 * @package     Piksel\Kigo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PropertyReviewTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PropertyReview"
     */
    public function testPropertyReview()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "rating"
     */
    public function testPropertyRating()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "check_in_date"
     */
    public function testPropertyCheckInDate()
    {
    }

    /**
     * Test attribute "check_out_date"
     */
    public function testPropertyCheckOutDate()
    {
    }

    /**
     * Test attribute "review_date"
     */
    public function testPropertyReviewDate()
    {
    }

    /**
     * Test attribute "reviewer_name"
     */
    public function testPropertyReviewerName()
    {
    }
}
