<?php
/**
 * PropertyLocalizedDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Patrick Leijser
 * @link     http://patrickleijser.nl
 */

/**
 * Kigo Core API
 *
 * https://www.kigoapis.com/core/v0.8/swagger/
 *
 * The version of the Kigo Core API: v0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\Kigo;

use PHPUnit\Framework\TestCase;

/**
 * PropertyLocalizedDataTest Class Doc Comment
 *
 * @category    Class
 * @description PropertyLocalizedData
 * @package     Piksel\Kigo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PropertyLocalizedDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PropertyLocalizedData"
     */
    public function testPropertyLocalizedData()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "descriptions"
     */
    public function testPropertyDescriptions()
    {
    }

    /**
     * Test attribute "amenities"
     */
    public function testPropertyAmenities()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "videos"
     */
    public function testPropertyVideos()
    {
    }

    /**
     * Test attribute "virtual_tours"
     */
    public function testPropertyVirtualTours()
    {
    }
}
