<?php
/**
 * SolutionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Patrick Leijser
 * @link     http://patrickleijser.nl
 */

/**
 * Kigo Core API
 *
 * https://www.kigoapis.com/core/v0.8/swagger/
 *
 * The version of the Kigo Core API: v0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\Kigo;

use PHPUnit\Framework\TestCase;

/**
 * SolutionTest Class Doc Comment
 *
 * @category    Class
 * @description Solution
 * @package     Piksel\Kigo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SolutionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Solution"
     */
    public function testSolution()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "supported_locales"
     */
    public function testPropertySupportedLocales()
    {
    }

    /**
     * Test attribute "primary_locale"
     */
    public function testPropertyPrimaryLocale()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "office"
     */
    public function testPropertyOffice()
    {
    }

    /**
     * Test attribute "accepted_cards"
     */
    public function testPropertyAcceptedCards()
    {
    }

    /**
     * Test attribute "payment_gateways"
     */
    public function testPropertyPaymentGateways()
    {
    }
}
