<?php
/**
 * PropertyImagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Patrick Leijser
 * @link     http://patrickleijser.nl
 */

/**
 * Kigo Core API
 *
 * https://www.kigoapis.com/core/v0.8/swagger/
 *
 * The version of the Kigo Core API: v0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Piksel\Kigo;

use \Piksel\Kigo\Configuration;
use \Piksel\Kigo\ApiException;
use \Piksel\Kigo\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PropertyImagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Patrick Leijser
 * @link     http://patrickleijser.nl
 */
class PropertyImagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteImage
     *
     * Delete Property Image.
     *
     */
    public function testDeleteImage()
    {
    }

    /**
     * Test case for postImage
     *
     * Create Property Image.
     *
     */
    public function testPostImage()
    {
    }

    /**
     * Test case for putImage
     *
     * Update Property Image (image urls can't be modified).
     *
     */
    public function testPutImage()
    {
    }
}
